from .async_mock import AsyncMock

_AUTH_RESPONSE = '''{
    "platformType": "uplay",
    "ticket": "LongTicket",
    "twoFactorAuthenticationTicket": None,
    "profileId": "12345",
    "userId": "Mock",
    "nameOnPlatform": "KptMock",
    "environment": "Prod",
    "expiration": "2019-03-05T11:28:49.0783145Z",
    "spaceId": "1234",
    "clientIp": "420.BL.4ZE.IT",
    "clientIpCountry": "US",
    "serverTime": "2019-03-05T08:28:49.0792996Z",
    "sessionId": "Session_id",
    "sessionKey": "Session_key",
    "rememberMeTicket": "Rememeber_me"
}'''


class BackendClientMock(AsyncMock):
    def authorize(self, auth_code):
        pass

    def set_auth_lost_callback(self, callback):
        pass

    def is_authenticated(self):
        return True

    async def authorise_with_stored_credentials(self, credentials):
        return await self.get_user_data()

    async def authorise_with_cookies(self, credentials):
        return {'userId': '123', 'username': 'Mock'}

    def restore_credentials(self, data):
        pass

    async def get_user_data(self):
        return {'userId': '123', 'username': 'Mock', 'nameOnPlatform': 'MockPl', 'accountIssues': None,
                'communicationOptIn': True, 'communicationThirdPartyOptIn': False, 'country': 'US',
                'dateCreated': '2017-11-06T17:57:05.9770000Z', 'dateOfBirth': '1990-01-01T00:00:00.0000000Z',
                'email': 'mocker@gmail.com', 'firstName': None, 'gender': None, 'hasAcceptedLegalOptins': True,
                'lastName': None, 'preferredLanguage': 'en',
                'status': {'autoGeneratedUsername': False, 'dateOfBirthApproximated': False, 'invalidEmail': False,
                           'missingRequiredInformation': False, 'pendingDeactivation': False,
                           'recoveringPassword': False, 'passwordUpdateRequired': False, 'reserved': False,
                           'changeEmailPending': False, 'inactiveAccount': False, 'generalStatus': 'activated',
                           'suspiciousActivity': False, 'locked': False}, 'accountType': 'Ubisoft'}

    async def get_game_stats(self, space_id):
        return {'Statscards': []}

    async def get_friends(self):
        return {'friends': [{'pid': '420', 'nameOnPlatform': 'mocker1', 'lastModified': '2018-12-27T00:00:00.0000000',
                             'state': 'Friends'},
                            {'pid': '123', 'nameOnPlatform': 'mocker2', 'lastModified': '2019-03-29T00:00:00.0000000',
                             'state': 'Friends'},
                            {'pid': '321', 'nameOnPlatform': 'mocker3', 'lastModified': '2019-05-14T00:00:00.0000000',
                             'state': 'Friends'}]}

    async def get_subscription_titles(self):
        return None

    async def get_entitlements(self):
        return {
            "entitlements": [
              {
                "availability": "playable",
                "accessLevel": "owned",
                "type": "game",
                "spaceId": "6678eff0-1293-4f87-8c8c-06a4ca646068",
              },
              {
                "availability": "playable",
                "accessLevel": "owned",
                "type": "game",
                "spaceId": "f40e304d-8e8d-4343-8270-d06487c35add",
              },
              {
                "availability": "playable",
                "accessLevel": "owned",
                "type": "game",
                "spaceId": "6edd234a-abff-4e90-9aab-b9b9c6e49ff7",
              },
              {
                "availability": "playable",
                "accessLevel": "owned",
                "type": "game",
                "spaceId": "1d1273d9-2120-4e55-8d98-66e08781258e",
              },
              {
                "availability": "playable",
                "accessLevel": "owned",
                "type": "game",
                "spaceId": "50228b8c-bbaa-4c32-83c6-2831a1ac317c",
              },
              {
                "availability": "playable",
                "accessLevel": "owned",
                "type": "game",
                "spaceId": "4bd0476b-acec-446d-b526-23a0209101ca",
              },
            ]
        }

    async def get_applications(self, space_ids):
        _ALL_GAMES = {
            "6678eff0-1293-4f87-8c8c-06a4ca646068": "Assassin's Creed\u00ae Unity",
            "f40e304d-8e8d-4343-8270-d06487c35add": "Far Cry\u00ae 5",
            "6edd234a-abff-4e90-9aab-b9b9c6e49ff7": "Tom Clancy's The Division\u2122 ",
            "1d1273d9-2120-4e55-8d98-66e08781258e": "Trackmania Turbo",
            "50228b8c-bbaa-4c32-83c6-2831a1ac317c": "Far Cry\u00ae 3",
            "4bd0476b-acec-446d-b526-23a0209101ca": "Far Cry\u00ae 3 Blood Dragon",
        }
        games = []
        for sid in space_ids:
            if sid in _ALL_GAMES:
                games.append({"spaceId": sid, "name": _ALL_GAMES[sid], "platforms": [{"type": "PC"}]})
        return {"games": games}

    async def get_subscription(self):
        pass

    async def get_subscription_games(self):
        return []
